### ISSUE TITLE
Tutorial step 1 starts ngork processes and does not clean them up

### ISSUE THREAD

**Issue by davidgubler** [projectsyn/commodore-component-tutorial#8]
Each time the tutorial step 1 is run it starts an ngork process in the background. If the step 1 is run multiple times, these orphan processes break ngork, and prevent the script from proceeding past the "Waiting for Lieutenant API" step.

A workaround is to manually kill all ngork processes before starting the tutorial step 1 again.

**Comment by akosma** [comment]
Indeed this is not clearly explained, but one shouldn't run step 1 multiple times, instead use step 5 which includes a "killall ngrok" command. But this tutorial maybe deserves more love than just that.
