### ISSUE TITLE
Tutorial step 1 incompatible with Kubernetes 1.24

### ISSUE THREAD

**Issue by davidgubler** [projectsyn/commodore-component-tutorial#9]
The first (setup) step of the tutorial does not work with Kubernetes 1.24.

The problem is that the "Prepare Lieutenant API Authentication and Authorization" step creates a ServiceAccount, but no secret for it. This was fine with older Kubernetes versions because these automatically created a secret, however this changed in 1.24, and Kubernetes no longer generates this secret automatically.

For details see:
* https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md#urgent-upgrade-notes-1
* https://stackoverflow.com/questions/72256006/service-account-secret-is-not-listed-how-to-fix-it

Workaround:
Add "--kubernetes-version 1.22.4" to the "minikube start" command.

**Comment by tobru** [comment]
Kubernetes 1.24 is not yet supported by Project Syn. Work ongoing:

- https://github.com/projectsyn/lieutenant-operator/issues/229
- https://github.com/projectsyn/lieutenant-api/issues/185

**Comment by davidgubler** [comment]
@tobru thanks! I'll try to use an older kubernetes version.

**Comment by akosma** [comment]
Got the same error when rewriting the getting started guide for Syn, and using 1.23 helped.

**Comment by akosma** [comment]
@tobru I see that the two issues you mention have been solved, can we close this issue?

**Comment by tobru** [comment]
If the tutorial works now, yes. Haven't tested myself, I just mentioned the two issues.

**Comment by simu** [comment]
From what I can see, we still need to update the tutorial to use a version of the Lieutenant operator and API which actually support K8s 1.24+ (Lieutenant operator v1.4.0 or newer, and Lieutenant API v0.10.1 or newer respectively). Additionally, you'll need to set `LIEUTENANT_CREATE_SERVICEACCOUNT_TOKEN_SECRET=true` for the Lieutenant operator. 

See also https://syn.tools/lieutenant-operator/references/configuration.html
